// <auto-generated>
// Rewired Constants
// This list was generated on 2022-04-08 1:38:17 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Movement
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement", friendlyName = "Move Horizontal")]
        public const int Move_Horizontal = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement", friendlyName = "Move Vertical")]
        public const int Move_Vertical = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement", friendlyName = "Face Point")]
        public const int Face_Point = 4;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
